spring:
  config:
    activate:
      on-profile: "dev"
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: com.example.howmuch.config.app.UpperCaseNamingStrategy
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 100
fcm:
  path: ${FCM_PATH}

